-- MySQL Script generated by MySQL Workbench
-- 01/21/16 14:25:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema game
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema game
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `game` DEFAULT CHARACTER SET utf8 ;
USE `game` ;

-- -----------------------------------------------------
-- Table `game`.`weapon_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`weapon_types` (
  `weapon_type_id` INT NOT NULL AUTO_INCREMENT,
  `weapon_type_name` VARCHAR(45) NULL,
  PRIMARY KEY (`weapon_type_id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`.`weapon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`weapon` (
  `weapon_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `damage_minimal` INT NOT NULL,
  `damage_maximal` INT NOT NULL,
  `str_b` INT NULL,
  `agi_b` INT NULL,
  `int_b` INT NULL,
  `weapon_type` INT NULL,
  PRIMARY KEY (`weapon_id`),
  INDEX `weapontypedict_idx` (`weapon_type` ASC),
  CONSTRAINT `weapontypedict`
  FOREIGN KEY (`weapon_type`)
  REFERENCES `game`.`weapon_types` (`weapon_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`.`armor_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`armor_types` (
  `armor_type_id` INT NOT NULL,
  `armor_type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`armor_type_id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`.`armor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`armor` (
  `armor_id` INT NOT NULL AUTO_INCREMENT,
  `armor_type` INT NULL,
  `name` VARCHAR(45) NULL,
  `str_b` INT NULL,
  `int_b` INT NULL,
  `agi_b` INT NULL,
  `armor_amount` INT NULL,
  PRIMARY KEY (`armor_id`),
  INDEX `armor_idx` (`armor_type` ASC),
  CONSTRAINT `armor`
  FOREIGN KEY (`armor_type`)
  REFERENCES `game`.`armor_types` (`armor_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
